on: [push, pull_request]

name: Lint
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build
      - run: bun lint
